global:
  config_version: 3
input:
  type: file
  path: /etc/grok-exporter/grok_exporter-1.0.0.RC3.linux-amd64/example/usb_activity.log
  readall: true
grok:
  patterns_dir: ./patterns
grok_patterns:
  - 'DEVICE [^=]*$'
metrics:
- type: counter
  name: usb_activity
  help: Exibe se um dispositivo USB está conectado ou não
  match: '%{DEVICE:device}'
  cumulative: false
  labels:
      device: '{{.device}}'
server:
  protocol: http
  port: 9144
